package schedule.domain.struct;
// Generated 08.05.2016 21:15:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.validation.constraints.NotNull;


/**
 * LecturerJobId generated by hbm2java
 */
@Embeddable
public class LecturerJobId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	@Column(name = "id_lecturer", updatable = false)
	@NotNull
	private int idLecturer;
	
	@Column(name = "id_chair", updatable = false)
	@NotNull
	private int idChair;
	
	public int getIdLecturer() {
		return idLecturer;
	}
	
	public void setIdLecturer(int idLecturer) {
		this.idLecturer = idLecturer;
	}
	
	public int getIdChair() {
		return idChair;
	}
	
	public void setIdChair(int idChair) {
		this.idChair = idChair;
	}
	
	public boolean equals(Object other) {
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof LecturerJobId)) return false;
		LecturerJobId castOther = (LecturerJobId) other;
		
		return (this.getIdLecturer() == castOther.getIdLecturer())
				&& (this.getIdChair() == castOther.getIdChair());
	}
	
	public int hashCode() {
		int result = 17;
		
		result = 37 * result + this.getIdLecturer();
		result = 37 * result + this.getIdChair();
		return result;
	}
	
}
