package schedule.domain.struct;
// Generated 08.05.2016 21:15:35 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import schedule.domain.persons.Lecturer;


/**
 * LecturerJob generated by hbm2java
 */
@Entity
@Table(name = "lecturer_job")
public class LecturerJob {
	
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(	name = "idLecturer",
								column = @Column(name = "id_lecturer")),
			@AttributeOverride(	name = "idChair",
								column = @Column(name = "id_chair")) })
	private LecturerJobId id;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@NotNull
	@JoinColumn(name = "id_chair", insertable = false, updatable = false)
	private Chair chair;
	
	@Enumerated(EnumType.STRING)
	@Column(name = "id_job", columnDefinition = "enum('pr','doc','stp')")
	@NotNull
	private JobType jobType;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@NotNull
	@JoinColumn(name = "id_lecturer", insertable = false, updatable = false)
	private Lecturer lecturer;
	
	public Chair getChair() {
		return chair;
	}
	
	public void setChair(Chair chair) {
		this.chair = chair;
	}
	
	public LecturerJobId getId() {
		return id;
	}
	
	public void setId(LecturerJobId id) {
		this.id = id;
	}
	
	public JobType getJobType() {
		return jobType;
	}
	
	public void setJobType(JobType jobType) {
		this.jobType = jobType;
	}
	
	public Lecturer getLecturer() {
		return lecturer;
	}
	
	public void setLecturer(Lecturer lecturer) {
		this.lecturer = lecturer;
	}
	
	public enum JobType {
		doc, pr, stp;
	}
	
}
