package schedule.domain.persons;
// Generated 08.05.2016 21:15:35 by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ElementCollection;
import javax.persistence.Embeddable;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotEmpty;


/**
 * Lecturer generated by hbm2java
 */
@Entity
@Table(name = "lecturer")
@PrimaryKeyJoinColumn(name = "id_lecturer", referencedColumnName = "uid")
@Embeddable
public class Lecturer extends Person {
	
	@Enumerated(EnumType.STRING)
	@Column(name = "degree", columnDefinition = "enum(dtn,ctn)")
	@NotNull
	private Degree degree;
	
	@OneToMany(mappedBy = "id.lecturer", cascade = CascadeType.ALL)
	@Valid
	@ElementCollection(targetClass = LecturerJob.class)
	@NotEmpty
	private List<LecturerJob> lecturerJobs = new ArrayList<LecturerJob>();
	
	public Degree getDegree() {
		return degree;
	}
	
	public void setDegree(Degree degree) {
		this.degree = degree;
	}
	
	public List<LecturerJob> getLecturerJobs() {
		return lecturerJobs;
	}
	
	public void setLecturerJobs(List<LecturerJob> lecturerJobs) {
		this.lecturerJobs = lecturerJobs;
	}
	
	public enum Degree {
		dtn, ctn;
	}
	
}
