package schedule.domain.persons;
// Generated 08.05.2016 21:15:35 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import schedule.domain.Group;


/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student")
@PrimaryKeyJoinColumn(name = "id_student", referencedColumnName = "uid")
public class Student extends Person {
	
	private Group group;
	private int recordBookNumber;
	
	public Student() {}
	
	public Student(Group group, int recordBookNumber) {
		this.group = group;
		this.recordBookNumber = recordBookNumber;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_group", nullable = false)
	public Group getGroup() {
		return this.group;
	}
	
	public void setGroup(Group group) {
		this.group = group;
	}
	
	@Column(name = "record_book_number", updatable = false, nullable = false)
	public int getRecordBookNumber() {
		return this.recordBookNumber;
	}
	
	public void setRecordBookNumber(int recordBookNumber) {
		this.recordBookNumber = recordBookNumber;
	}
	
}
